# Generated by Django 2.2 on 2021-06-26 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('py_belt_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='content',
            new_name='description',
        ),
    ]
